apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-app-1
  namespace: app-1
spec:
  interval: 1m0s
  ref:
    branch: demo
  url: https://github.com/Eugentk/flux-demo.git